[project]
name = "ai-search-algorithms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.0.1",
    "numpy>=2.3.4",
    "tqdm>=4.67.1",
]
